version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kordchat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: kordchat
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - kordchat-db-data:/var/lib/postgresql/data

volumes:
  kordchat-db-data: