basePath: /api
definitions:
  dtos.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dtos.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server KordChat
  title: KordChat API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: validate email and password to create JWT Token
      parameters:
      - description: Login data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User login successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid Data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Invalid email or password
          schema:
            additionalProperties: true
            type: object
      summary: Login
      tags:
      - Auth
  /refresh:
    post:
      consumes:
      - application/json
      description: use refresh token to create new access token
      produces:
      - application/json
      responses:
        "200":
          description: create access token successfully
          schema:
            additionalProperties: true
            type: object
        "401":
          description: invalid refresh token
          schema:
            additionalProperties: true
            type: object
      summary: create new access token
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: request Username, Email, Password to create User
      parameters:
      - description: Register
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: register user successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: invalid data
          schema:
            additionalProperties: true
            type: object
      summary: User register
      tags:
      - Auth
swagger: "2.0"
