basePath: /api
definitions:
  dtos.ChannelResponse:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      serverId:
        type: string
      type:
        type: string
      updatedAt:
        type: string
    type: object
  dtos.CreateChannelRequest:
    properties:
      name:
        type: string
      type:
        type: string
    required:
    - name
    type: object
  dtos.CreateMessageRequest:
    properties:
      content:
        type: string
    required:
    - content
    type: object
  dtos.CreateServerRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  dtos.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dtos.MessageResponse:
    properties:
      channelId:
        type: string
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      updatedAt:
        type: string
      user:
        $ref: '#/definitions/dtos.UserResponse'
    type: object
  dtos.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  dtos.ServerResponse:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      ownerId:
        type: string
      updatedAt:
        type: string
    type: object
  dtos.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server KordChat
  title: KordChat API
  version: "1.0"
paths:
  /channels/{channelId}/messages:
    get:
      consumes:
      - application/json
      description: Retrieve all messages for a specific channel
      parameters:
      - description: Channel ID
        in: path
        name: channelId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Messages retrieved successfully
          schema:
            items:
              $ref: '#/definitions/dtos.MessageResponse'
            type: array
        "400":
          description: Invalid data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Get all messages in a channel
      tags:
      - Message
    post:
      consumes:
      - application/json
      description: Create a new message in a channel
      parameters:
      - description: Channel ID
        in: path
        name: channelId
        required: true
        type: string
      - description: CreateMessage
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateMessageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Message created successfully
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "400":
          description: Invalid data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Create a new message
      tags:
      - Message
  /login:
    post:
      consumes:
      - application/json
      description: validate email and password to create JWT Token
      parameters:
      - description: Login data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User login successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid Data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Invalid email or password
          schema:
            additionalProperties: true
            type: object
      summary: Login
      tags:
      - Auth
  /refresh:
    post:
      consumes:
      - application/json
      description: use refresh token to create new access token
      produces:
      - application/json
      responses:
        "200":
          description: create access token successfully
          schema:
            additionalProperties: true
            type: object
        "401":
          description: invalid refresh token
          schema:
            additionalProperties: true
            type: object
      summary: create new access token
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: request Username, Email, Password to create User
      parameters:
      - description: Register
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: register user successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: invalid data
          schema:
            additionalProperties: true
            type: object
      summary: User register
      tags:
      - Auth
  /servers:
    get:
      consumes:
      - application/json
      description: Get servers list by userID
      produces:
      - application/json
      responses:
        "200":
          description: Servers List
          schema:
            items:
              $ref: '#/definitions/dtos.ServerResponse'
            type: array
        "400":
          description: invalid data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Get User's Servers
      tags:
      - Server
    post:
      consumes:
      - application/json
      description: request server name to create new server
      parameters:
      - description: CreateServer
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateServerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: create server successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: invalid data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Create new server
      tags:
      - Server
  /servers/{serverId}/channels:
    get:
      consumes:
      - application/json
      description: Get all channels in a server
      parameters:
      - description: Server ID
        in: path
        name: serverId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Channels retrieved successfully
          schema:
            items:
              $ref: '#/definitions/dtos.ChannelResponse'
            type: array
        "400":
          description: Invalid data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Get channels by server ID
      tags:
      - Channel
    post:
      consumes:
      - application/json
      description: Create a new channel in a server
      parameters:
      - description: Server ID
        in: path
        name: serverId
        required: true
        type: string
      - description: CreateChannel
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateChannelRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Channel created successfully
          schema:
            $ref: '#/definitions/dtos.ChannelResponse'
        "400":
          description: Invalid data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Create a new channel
      tags:
      - Channel
swagger: "2.0"
